aplus/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.urls import include, path
from django.contrib import admin


import shibboleth_login.urls
import social_django.urls
import userprofile.urls
import course.urls, course.long_urls
import exercise.urls
import edit_course.urls
import deviations.urls
import notification.urls
import external_services.urls
import news.urls
import diploma.urls
import apps.urls
import api.urls_v2
import redirect_old_urls.urls
import comments.urls

admin.autodiscover()

#  Pay attention to the order the URL patterns will be matched!
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^shibboleth/', include(shibboleth_login.urls)),
    url('', include(social_django.urls, namespace='social')),
    url(r'^api/v(?P<version>(2))/', include(api.urls_v2)), # why version in url? doc/api_versioning.md
    url(r'^accounts/', include(userprofile.urls)),
    url(r'^diploma/', include(diploma.urls)),
    url(r'^', include(redirect_old_urls.urls)),
    url(r'^', include(apps.urls)),
    url(r'^', include(news.urls)),
    url(r'^', include(external_services.urls)),
    url(r'^', include(course.long_urls)),
    url(r'^', include(deviations.urls)),
    url(r'^', include(edit_course.urls)),
    url(r'^', include(notification.urls)),
    url(r'^', include(exercise.urls)),
    url(r'^', include(course.urls)),
    url(r'^', include(comments.urls)),
]

if settings.DEBUG:
    import django.views.static, debug_toolbar
    urlpatterns.insert(0, url(r'^media/(?P<path>.*)$', django.views.static.serve,
        { 'document_root': settings.MEDIA_ROOT }))

    # django debug tools
    urlpatterns = [
                  path('__debug__/', include(debug_toolbar.urls)),

                  # For django versions before 2.0:
                  # url(r'^__debug__/', include(debug_toolbar.urls)),

              ] + urlpatterns

apps/urls.py
from django.conf.urls import url

from course.urls import INSTANCE_URL_PREFIX
from . import views

urlpatterns = [
    url(INSTANCE_URL_PREFIX + r'tabs/(?P<tab_id>\d+)/$',
    views.TabView.as_view(),
    name="apps-tab"),
]

comments/urls.py
from django.urls import path
from django.conf.urls import url

from course.urls import INSTANCE_URL_PREFIX, MODULE_URL_PREFIX, \
    USER_URL_PREFIX, EDIT_URL_PREFIX

from exercise.urls import EXERCISE_URL_PREFIX
from . import views
 
app_name = 'comments'
urlpatterns = [
    url(EXERCISE_URL_PREFIX+r'comment/(?P<post_pk>\d+)/$', views.comment, name='comment'),
]

easy_comment/urls.py
from django.conf.urls import url

from . import views


app_name = 'easy_comment'
urlpatterns = [
    url(r'^submit-comment/$', views.submit_comment, name='submit_comment'),
    url(r'^entry/(?P<pk>\d+)/comment-list/', views.comment_list, name='comment_list'),
    url(r'^comment-list/$', views.comment_list, name='comment_list_no_object')
]

comments/models.py
from django.db import models
from mptt.models import MPTTModel, TreeForeignKey
# Create your models here.
from django.utils import timezone

class Comment(models.Model):
    name = models.CharField('名字', max_length=50)
    text = models.TextField('内容')
    created_time = models.DateTimeField('创建时间', default=timezone.now)
    post = models.ForeignKey('exercise.LearningObject', verbose_name='练习', on_delete=models.CASCADE)

    class Meta:
        verbose_name = '评论'
        verbose_name_plural = verbose_name

    def __str__(self):
        return '{}: {}'.format(self.name, self.text[:20])

class CommentMultip(MPTTModel):
    name = models.CharField('名字',max_length=50)
    text = models.TextField('内容')
    created_time = models.DateTimeField('创建时间', default=timezone.now)
    commentobject = models.ForeignKey(Comment, verbose_name='一级评论', on_delete=models.CASCADE, related_name='replies')#对应属于上一级评论
    parent = TreeForeignKey('self', on_delete=models.CASCADE, null=True, blank=True, related_name='children', verbose_name='回复对象')
    
    class Meta:
        verbose_name = '多级评论'
        verbose_name_plural = verbose_name

    class MPTTMeta:
        order_insertion_by = ['created_time']
        
        

    def __str__(self):
        return '{}: {}'.format(self.name, self.text[:20])

easy_comment/models.py
from mptt.models import TreeForeignKey, MPTTModel
from ckeditor_uploader.fields import RichTextUploadingField
from django.db import models
from django.conf import settings
from django.core.cache import cache
from django.template.loader import render_to_string
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes.fields import GenericForeignKey

# Create your models here.


class Comment(MPTTModel):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, blank=True, null=True,)
    content_type = models.ForeignKey(ContentType, blank=True, null=True)
    object_id = models.PositiveIntegerField(blank=True, null=True, db_index=True)
    content_object = GenericForeignKey('content_type', 'object_id')
    parent = TreeForeignKey('self', blank=True, null=True, verbose_name='父级评论')
    content = RichTextUploadingField(verbose_name='评论', config_name='default')
    created = models.DateTimeField(auto_now_add=True, verbose_name='提交时间')

    class MPTTMeta:
        order_insertion_by = ['created']

    def __str__(self):
        if self.parent is not None:
            return '{} 回复 {}'.format(self.user.username, self.parent.user.username)
        if self.content_object:
            return '{} 评论 {}_{}'.format(self.user.username, self.content_type.model, self.object_id)
        else:
            return '{} 发表了评论'.format(self.user.username)

    def to_html(self):
        """
        把每一条comment的内容渲染成html，并保存在缓存里，不需要每次都渲染了
        :return html
        """
        key = "comment_{}_html".format(self.id)
        html = cache.get(key)
        if not html:
            html = render_to_string('easy_comment/comment_entry.html', context={'comment': self})
            cache.set(key, html, timeout=600)
        return html

comments/forms.py
from django import forms
from .models import Comment
 
 
class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['name', 'text']

easy_comment/forms.py
from django import forms
from django.template.defaultfilters import striptags

from .models import Comment


class CommentForm(forms.ModelForm):
    honeypot = forms.CharField(required=False,
                               label='If you enter anything in this field, you comment will be treated as spam!')

    class Meta:
        model = Comment
        fields = ('content', 'parent', 'content_type', 'object_id')

    def clean_content(self):
        """
        检查content字段是否为空
        """
        value = self.cleaned_data['content']
        if striptags(value).replace(' ', '').replace('&nbsp;', '') == '' and '<img' not in value:
            self.add_error('content', '兄dei，评论内容不能为空~')
        return value

comments/views.py
from django.shortcuts import render

# Create your views here.
from exercise.models import LearningObject
from django.shortcuts import get_object_or_404, redirect, render
from django.views.decorators.http import require_POST
from authorization.permissions import ACCESS
from course.viewbase import CourseInstanceBaseView, CourseInstanceMixin
from lib.viewbase import BaseRedirectMixin, BaseView
from exercise.viewbase import ExerciseBaseView
from course.viewbase import CourseInstanceBaseView, EnrollableViewMixin

@require_POST
def comment(request, post_pk):
    access_mode = ACCESS.ENROLLED
    # 先获取被评论的文章，因为后面需要把评论和被评论的文章关联起来。
    # 这里我们使用了 django 提供的一个快捷函数 get_object_or_404，
    # 这个函数的作用是当获取的文章（Post）存在时，则获取；否则返回 404 页面给用户。
    # modelwithinheritance_ptr_id
    learningobject = get_object_or_404(LearningObject, id=post_pk)
 
    # django 将用户提交的数据封装在 request.POST 中，这是一个类字典对象。
    # 我们利用这些数据构造了 CommentForm 的实例，这样就生成了一个绑定了用户提交数据的表单。
    form = CommentForm(request.POST)
 
    # 当调用 form.is_valid() 方法时，django 自动帮我们检查表单的数据是否符合格式要求。
    if form.is_valid():
        # 检查到数据是合法的，调用表单的 save 方法保存数据到数据库，
        # commit=False 的作用是仅仅利用表单的数据生成 Comment 模型类的实例，但还不保存评论数据到数据库。
        comment = form.save(commit=False)
 
        # 将评论和被评论的文章关联起来。
        comment.post = learningobject
 
        # 最终将评论数据保存进数据库，调用模型实例的 save 方法
        comment.save()
 
        # 重定向到 post 的详情页，实际上当 redirect 函数接收一个模型的实例时，它会调用这个模型实例的 get_absolute_url 方法，
        # 然后重定向到 get_absolute_url 方法返回的 URL。
        return redirect(learningobject)
        #return HttpResponseRedirect('/')
 
    # 检查到数据不合法，我们渲染一个预览页面，用于展示表单的错误。
    # 注意这里被评论的文章 post 也传给了模板，因为我们需要根据 post 来生成表单的提交地址。
    context = {
        'post': post,
        'form': form,
    }
    return render(request, 'comments/preview.html', context=context)

easy_comment/views.py
from django.apps import apps
from django.conf import settings
from django.http import JsonResponse
from django.views.decorators.http import require_POST
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger, InvalidPage
from django.contrib.contenttypes.models import ContentType

import easy_comment.handlers
from easy_comment.forms import CommentForm
from easy_comment.templatetags.comment_tags import get_comments_user_count, get_comment_list

# Create your views here.


# 该视图函数只接受post请求, 只允许登录用户评论
@require_POST
@login_required
def submit_comment(request):
    """
    通过前端ajax post数据，生成评论，并返回评论对应的html和参与评论的用户数量、评论数量
    :param request:
    :return: JsonResponse
    """
    form = CommentForm(data=request.POST)
    if form.is_valid():
        new_comment = form.save(commit=False)
        new_comment.user = request.user
        type_id = request.POST.get('content_type')
        object_id = request.POST.get('object_id')
        if type_id and object_id:
            content_type = ContentType.objects.get_for_id(type_id)
            content_object = content_type.get_object_for_this_type(id=object_id)
        else:
            content_object = None
        new_comment.content_object = content_object
        new_comment.save()
        cmt_list = get_comment_list(content_object).order_by('-created')
        user_count = get_comments_user_count(entry=content_object)
        comment_count = cmt_list.count()
        paginate_by = getattr(settings, 'COMMENT_PAGINATE_BY', 10)
        if paginate_by:
            cmt_list = cmt_list[: paginate_by]
        comment_list_html = ''
        for comment in cmt_list:
            comment_list_html += comment.to_html()
        return JsonResponse({'msg': 'success!',
                             'html': comment_list_html,
                             'user_count': user_count,
                             'comment_count': comment_count})
    # 如果content字段出问题了，把error记录在msg里，在前端alert
    if form.errors.as_data()['content']:
        msg = form.errors.as_data()['content'][0].message
    else:
        msg = '评论出错啦！'
    return JsonResponse({"msg": msg})


def comment_list(request, pk=None):
    """
    获取评论list，如果settings.py里设置了COMMENT_PAGINATE_BY(默认10)，则对评论分页
    设置 COMMENT_PAGINATE_BY = None则不分页
    把每一条评论的html加在一起，生成所有评论的html
    jsonresponse 里返回html，评论数量、评论人数
    :param request:
    :param pk: 被评论模型（example：文章）的pk
    :return: JsonResponse
    """
    try:
        type_id = request.GET.get('content_type')
        content_type = ContentType.objects.get_for_id(type_id)
        entry = content_type.get_object_for_this_type(id=pk)
    except Exception as e:
        entry = None
    paginate_by = getattr(settings, 'COMMENT_PAGINATE_BY', 10)
    cmt_list = get_comment_list(entry=entry).order_by('-created')
    comment_count = cmt_list.count()
    user_count = get_comments_user_count(entry=entry)
    if paginate_by:
        paginator = Paginator(cmt_list, paginate_by)
        page = request.GET.get('page', 1)
        try:
            cmt_list = paginator.page(page)
        except PageNotAnInteger:
            cmt_list = paginator.page(1)
        except EmptyPage:
            cmt_list = []
    comment_list_html = ''
    for comment in cmt_list:
        comment_list_html += comment.to_html()
    return JsonResponse({'html': comment_list_html,
                         'user_count': user_count,
                         'comment_count': comment_count})

easy_comment/templates/easy_comment/comment.html
{% load comment_tags %}
{% load staticfiles %}
<div class="pinglun" id="评论">
    <div class="comment-form-header">
        {% if request.user.is_authenticated %}
        <!-- 设置你的头像 -->
        <img src="{{ request.user.avatar.url }}">
        <div class="header-username">
            <span>
                {{ request.user.username }}
                <i class="fa fa-edit"></i>
            </span>
            <span id="reply-action">回复：</span>
            <span id="recipient"></span>
        </div>
        {% else %}
        <!-- 设置登录链接 -->
        <span class="remind-login">尚未登录，请<a href="#">登录</a>后参与评论</span>
        {% endif %}
    </div>
    {% generate_form entry as form %}
    <form class="comment-form" method="post" action="{% url 'easy_comment:submit_comment' %}">
        {% csrf_token %}
        {{ form.media }}
        {% for field in form %}
        {{ field }}
        {{ field.errors }}
        {% endfor %}
        <button class="button button-primary-flat button-rounded pull-right {% if not request.user.is_authenticated %}
        no-login
        {% endif %}" type="submit" id="submit-button">
            <i class="fa fa-check-square-o"></i>
            提交评论
        </button>
    </form>
    <button class="button button-primary-flat button-rounded pull-right" id="cancel-button">
        <i class="fa fa-undo"></i>
        取消回复
    </button>
    <div class="clear"></div>

    <h2>
        评论
        <span class="pull-right"></span>
    </h2>
    <div class="pinglun-list">
    </div>
</div>
<!-- 提交评论 回复 各种ajax -->
<script>
    $('.pinglun-text img').removeAttr('style');
    $(".django-ckeditor-widget").removeAttr('style');
    // 提交评论按钮
    $("#submit-button").click(function (e) {
        e.preventDefault();
        if ($(this).hasClass('no-login')){
            alert("请登录后参与评论！");
            return false;
        }
        // 验证honeypot字段是否为空，如果不为空，则是垃圾评论
        if ($("#id_honeypot").val().length > 0){
                alert("spam!");
                return false;
        }
        // 默认从表单获取父级评论id，如果是回复的话，从sessionStorage提取
        pid = $('#id_parent option:selected').val();
        if (sessionStorage.getItem('reply')) {
            pid = sessionStorage.getItem('pid');
        }
        $.ajaxSetup({
            data: {csrfmiddlewaretoken: '{{ csrf_token }}' }});
        $.ajax({
            type: 'post',
            url: "{% url 'easy_comment:submit_comment' %}",
            data:{
                    'honeypot':$("#id_honeypot").val(),
                    'content':CKEDITOR.instances.id_content.getData(),
                    'parent':pid,
                    'content_type':$('#id_content_type option:selected').val(),
                    'object_id': $('#id_object_id').val()
            },
            dataType:'json',
            success:function (data) {
                // 评论提交成功
                if (data.msg == 'success!') {
                    // 加载评论html
                    $(".pinglun-list").html(data.html);
                    // 清空编辑框内容
                    CKEDITOR.instances.id_content.setData("");
                    $("#cancel-button").css('display', 'none');
                    $("#reply-action").css('display', 'none');
                    $("#recipient").css('display', 'none');
                    sessionStorage.removeItem('reply');
                    // 获取参与人数，评论数量
                    $('.pinglun h2 span').text(data.user_count + "人参与 | " + data.comment_count + "条评论");
                    $('.pinglun-text img').removeAttr('style');
                    Prism.highlightAll();
                    empty_page = false;
                    block_request = false;
                    page = 1;
                }
                else {
                    alert(data.msg);
                }
            },
            error:function (data) {
                alert("Something is wrong! lol");
            }
        });
    });
    // 点击回复按钮，使用.live()绑定click事件，因为我们会使用ajax加载评论
    $(".reply").live('click', function () {
        if ($("#submit-button").hasClass('no-login')) {
            alert('请登录后参与评论！');
            return false;
        }
        // 评论框显示被回复的用户名，显示取消回复按钮
        $("#recipient").text($(this).data('name')).css('display', 'inline-block');
        $("#reply-action").css('display', 'inline-block');
        $("#cancel-button").css('display', 'inline-block');
        sessionStorage.setItem('reply', true);
        // 获取父级评论的id存在session-storage里，提交评论时提取出来
        sessionStorage.setItem('pid', $(this).attr('id'));
    });
    // 取消回复按钮
    $("#cancel-button").click(function () {
        $(this).css('display', 'none');
        $("#reply-action").css('display', 'none');
        $("#recipient").css('display', 'none');
        sessionStorage.removeItem('reply');
    });
    // 从comment_list view获取评论html，评论人数，评论数量
    {% get_content_type_id entry as type_id %}
    var type_id = {{ type_id }}
    $.get(
        "{% url 'easy_comment:comment_list' entry.id %}",
        {'content_type': type_id},
        function (data) {
            $(".pinglun-list").html(data.html);
            Prism.highlightAll();
            $('.pinglun-text img').removeAttr('style');
            $('.pinglun h2 span').text( data.user_count + "人参与 | " + data.comment_count + "条评论");
        }
    );
    var page = 1;
    var empty_page = false;
    var block_request = false;
    // 滚动加载评论
    $(window).scroll(function () {
        var margin = $(document).height() - $(window).height() - 200;
        if ($(window).scrollTop() > margin && empty_page == false && block_request == false) {
            block_request = true;
            page += 1;
            $.get(
                "{% url 'easy_comment:comment_list' entry.id %}?page=" + page,
                {'content_type': type_id},
                function(data) {
                    if(data == '') {
                    empty_page = true;
                }
                else {
                    block_request = false;
                    $(".pinglun-list").append(data.html);
                    Prism.highlightAll();
                    $('.pinglun-text img').removeAttr('style');
                }
            });
        }
    });
</script>

easy_comment/templates/easy_comment/comment_entry.html
{% load staticfiles %}
<div class="pinglun-entry" id="c{{ comment.id }}">
    <div class="pinglun-avatar">
        <img src="{{ comment.user.avatar.url }}">
    </div>
    <div class="pinglun-body">
        <h3>
            {{ comment.user.username }}
            <span class="pull-right">{{ comment.submit_date|timesince }}</span>
        </h3>
        {% if comment.parent %}
        <div class="parent-pinglun">
            <blockquote>
                <em><i class="fa fa-quote-left"></i>{{ comment.parent.user.username }}</em><br>
                <div>{{ comment.parent.content|safe }}</div>
            </blockquote>
        </div>
        {% endif %}
        <div class="pinglun-text">{{ comment.content|safe }}</div>
    </div>
    <div class="clear"></div>
    <div class="pinglun-bottom">
        <a class="reply" id="{{ comment.id }}" href="#评论" data-name="{{ comment.user.username }}">
            <span class="pull-right">回复</span>
        </a>
        <div class="clear"></div>
    </div>
</div>